language: r
sudo: false
latex: false
pandoc: false
cache: packages

before_install:
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in twitter_taken.rds.enc -out twitter_taken.rds -d
  - git config --global user.email "xie@yihui.name"
  - git config --global user.name "Yihui Xie"

script:
  - Rscript R/fetch.R

after_success:
  - rm twitter_token.rds
  - git add --all *
  - git commit -m"Daily update"
  - git push -q https://${GITHUB_PAT}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:master
